In [1]:
import numpy as np

In [2]:
# Creating ID Arrays
arr1 = np.array([1., 2, 3])
print(arr1)

l1 = [2, 3, 4, 5]
arr2 = np.array(l1)
print(arr2)
print(type(arr2))

[1. 2. 3.]
[2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Creating 2D arrays
l = [[1, 2, 3], [2, 3, 4]]
arr3 = np.array(l)
print(arr3.shape)
print(arr3)

(2, 3)
[[1 2 3]
 [2 3 4]]


In [4]:
l = [[1, 2, 3], [2, 3, 4], [3, 5, 6]]
arr3 = np.array(l)
print(arr3.shape)
print(arr3)

(3, 3)
[[1 2 3]
 [2 3 4]
 [3 5 6]]


In [5]:
# dtype => np.float32, np.int3, str
arr4 = np.array(l, dtype=np.float32)
print(type(arr4[0][0]))
print(arr4)

<class 'numpy.float32'>
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 5. 6.]]


In [6]:
# arange
print(np.arange(1, 53, 7))

[ 1  8 15 22 29 36 43 50]


In [7]:
# reshape - acts on 1D arrays
arr5 = np.arange(1, 60, 7, dtype=np.float32).reshape(3, 3)
print(arr5)

[[ 1.  8. 15.]
 [22. 29. 36.]
 [43. 50. 57.]]


In [8]:
# flatten
arr6 = arr5.flatten()
print(arr6)

[ 1.  8. 15. 22. 29. 36. 43. 50. 57.]


In [9]:
# np.ones and np.zeros

print(np.ones(4))
print("\n")

# for multidimensional, pass in the shape as a tuple
shape = (2, 3)
ones = np.ones((3,4))
zeros = np.zeros((shape))
print(ones)
print("\n")
print(zeros)


[1. 1. 1. 1.]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# np.random

np.random.random((3,4))

array([[0.33504596, 0.61780346, 0.22727065, 0.95910505],
       [0.71119378, 0.61215727, 0.160726  , 0.74807288],
       [0.73371473, 0.66328514, 0.46830611, 0.50794304]])

In [11]:
# Random Integers using randint

random_ints = np.random.randint(5, 10, size=(3, 4))
print(random_ints)

[[9 8 8 9]
 [9 9 5 9]
 [7 7 9 7]]


In [12]:
# Constraining the range

a = 5 # lower bound
b = 10 # upper bound
random_array = np.random.random((3, 4)) * (b - a) + a
print(random_array)

[[7.90312865 6.15930228 6.11167041 5.47269965]
 [7.55436827 6.55700625 5.23474806 7.07373339]
 [7.08552765 9.52871915 9.27096701 7.96920633]]


In [13]:
# linspace - linearly spaced (equal distance)

print(np.linspace(1, 9, 3))

[1. 5. 9.]


In [14]:
# Identity matrix
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


ARRAY ATTRIBUTES

In [16]:
a1 = np.array([1,2, 3])
a4 = np.array([1,2, 3], dtype=np.float32)
a2 = np.array([[1,2, 3], [1, 3, 4]])
a3 = np.array([[1,2, 3], [1, 3, 4], [0,3, 1]])

In [17]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
np.sav

1
2
2


In [18]:
# shape

print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(3, 3)


In [19]:
# size

print(a1.size)
print(a2.size)
print(a3.size)

3
6
9


In [20]:
# item size

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)
print(a4.itemsize)

4
4
4
4


In [21]:
# changing datatype
a5 = a3.astype(np.float64)
print(a3.itemsize)
print(a5.itemsize)

4
8


In [22]:
# Numpy Array Operations
prices1 = np.array(
    [
        [1, 2, 3],
        [3, 4, 5],
        [1, 3, 4]
    ], dtype=np.float32
)

prices2 = np.array(
    [
        [3, 2, 3],
        [3, 7, 5],
        [9, 3, 4]
    ], dtype=np.float32
)

In [23]:
# Max, min
print(np.max(prices1))
print(np.min(prices2))

5.0
2.0


In [24]:
# Sum and product
print(np.product(prices1))
print(np.sum(prices2))

4320.0
39.0


SCALAR OPERATORS

In [26]:
# Scaler product
print(prices1 * 3)

# Relational
print(prices1 >= 3)

[[ 3.  6.  9.]
 [ 9. 12. 15.]
 [ 3.  9. 12.]]
[[False False  True]
 [ True  True  True]
 [False  True  True]]


VECTOR OPERATORS

In [28]:
print(prices1 * prices2)

[[ 3.  4.  9.]
 [ 9. 28. 25.]
 [ 9.  9. 16.]]


STATISTICS

In [30]:
print(np.mean(prices1))
print(np.median(prices1))
print(np.var(prices1))
print(np.std(prices1))

2.8888888
3.0
1.6543211
1.2862041


TRIGNOMETRIC FUNCTIONS

In [32]:
print(np.sin(prices1))

[[ 0.841471   0.9092974  0.14112  ]
 [ 0.14112   -0.7568025 -0.9589243]
 [ 0.841471   0.14112   -0.7568025]]


In [33]:
# Dot product 

print(np.dot(prices1, prices2))

[[36. 25. 25.]
 [66. 49. 49.]
 [48. 35. 34.]]


In [34]:
# Logs and Exponents

print(np.exp(prices1))
print(np.log(prices1))

[[  2.718282    7.3890557  20.085537 ]
 [ 20.085537   54.59815   148.41316  ]
 [  2.718282   20.085537   54.59815  ]]
[[0.        0.6931472 1.0986123]
 [1.0986123 1.3862944 1.609438 ]
 [0.        1.0986123 1.3862944]]


In [35]:
# floor, round and ceil
print(np.floor(prices1))
print(np.ceil(prices1))
print(np.round(prices1))

[[1. 2. 3.]
 [3. 4. 5.]
 [1. 3. 4.]]
[[1. 2. 3.]
 [3. 4. 5.]
 [1. 3. 4.]]
[[1. 2. 3.]
 [3. 4. 5.]
 [1. 3. 4.]]


In [36]:
# INDEXING and SLICING

print(prices1)
print(prices1[0,:])
col = prices1[:, 1]
print(col.shape)
print(prices1[0:2, 1:])

[[1. 2. 3.]
 [3. 4. 5.]
 [1. 3. 4.]]
[1. 2. 3.]
(3,)
[[2. 3.]
 [4. 5.]]


In [77]:
# Slicing 3D arrays
l = [
    [
        [3, 2, 3],
        [3, 7, 5],
        [9, 3, 4]
    ], 
    [
        [3, 2, 3],
        [3, 7, 5],
        [9, 3, 4]
    ]
]
three_d = np.array(l)
print(three_d.shape)
print(three_d[:,0:2,0:2])

(2, 3, 3)
[[[3 2]
  [3 7]]

 [[3 2]
  [3 7]]]


In [81]:
arr = np.arange(0,24, dtype=np.float32).reshape(2, 3, 4)
print(arr)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [93]:
print(arr[0])
print("\n")
print(arr[0,1:,1:3])
print("\n")
print(arr[1,:,2:])
print("\n")
print(arr[:,::2,2:])

[[[ 2.  3.]
  [10. 11.]]

 [[14. 15.]
  [22. 23.]]]


In [105]:
# Iteration

for i in np.nditer(arr):
    print(i)
    
for i in np.ravel(arr):
    print(i)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
21.0
22.0
23.0
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
21.0
22.0
23.0


In [115]:
# Transpose
print(arr.shape)
print(arr)
transposed = np.transpose(arr)
print(transposed.shape)
print(transposed)
print(transposed.T)

(2, 3, 4)
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
(4, 3, 2)
[[[ 0. 12.]
  [ 4. 16.]
  [ 8. 20.]]

 [[ 1. 13.]
  [ 5. 17.]
  [ 9. 21.]]

 [[ 2. 14.]
  [ 6. 18.]
  [10. 22.]]

 [[ 3. 15.]
  [ 7. 19.]
  [11. 23.]]]
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [123]:
# Horizontal stacking

h_stack = np.hstack((arr, arr))
v_stack = np.vstack((arr, arr))
print(h_stack)
print(v_stack)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]
  [12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]

 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [125]:
print(np.hsplit(h_stack, 2))
print(np.vsplit(v_stack, 2))

[array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]], dtype=float32), array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]], dtype=float32)]
[array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]], dtype=float32), array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]], dtype=float32)]
